# Generated by Django 4.2.2 on 2023-08-24 02:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
